<a href="https://colab.research.google.com/github/Divyanshucode93/GoogleColabsPractice/blob/main/HealthcareStroke_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import pandas as pd
import numpy as np

In [45]:
df = pd.read_csv('/content/healthcare-dataset-stroke-data.csv')

# **Set 1 (Questions 1–10)**
**Data Inspection & Basic Selection**

In [46]:
# Load the dataset healthcare-dataset-stroke-data.csv into a pandas DataFrame named df.
df    # df = pd.read_csv('/content/healthcare-dataset-stroke-data.csv')

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

In [47]:
# Display the first 5 rows of the DataFrame.
df.head(5)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [48]:
# How can you find the total number of rows and columns (the shape) of the dataset?
rows = df.shape[0]
columns = df.shape[1]

In [49]:
# Write the code to display the data types of all columns.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB

In [50]:
# Check the dataset for any missing (null) values and show the count of nulls for each column.
df.isna().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [51]:
# Display the summary statistics (mean, standard deviation, min, max, etc.) for the numerical columns.
df.describe()

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,5110.000000,5110.000000,5110.000000,5110.000000,5110.000000,4909.000000,5110.000000
mean,36517.829354,43.226614,0.097456,0.054012,106.147677,28.893237,0.048728
std,21161.721625,22.612647,0.296607,0.226063,45.283560,7.854067,0.215320
min,67.000000,0.080000,0.000000,0.000000,55.120000,10.300000,0.000000
25%,17741.250000,25.000000,0.000000,0.000000,77.245000,23.500000,0.000000
50%,36932.000000,45.000000,0.000000,0.000000,91.885000,28.100000,0.000000
75%,54682.000000,61.000000,0.000000,0.000000,114.090000,33.100000,0.000000
max,72940.000000,82.000000,1.000000,1.000000,271.740000,97.600000,1.000000

In [52]:
# Select and display only the gender column from the DataFrame.
df['gender']

0         Male
1       Female
2         Male
3       Female
4       Female
         ...
5105    Female
5106    Female
5107    Female
5108      Male
5109    Female
Name: gender, Length: 5110, dtype: object

In [53]:
# How do you display exactly the last 10 rows of the dataset?
df.tail(10)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
5100,68398,Male,82.0,1,0,Yes,Self-employed,Rural,71.97,28.3,never smoked,0
5101,36901,Female,45.0,0,0,Yes,Private,Urban,97.95,24.5,Unknown,0
5102,45010,Female,57.0,0,0,Yes,Private,Rural,77.93,21.7,never smoked,0
5103,22127,Female,18.0,0,0,No,Private,Urban,82.85,46.9,Unknown,0
5104,14180,Female,13.0,0,0,No,children,Rural,103.08,18.6,Unknown,0
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

In [54]:
# Find the count of each unique value in the smoking_status column (e.g., how many "smokes", "never smoked", etc.).
df['smoking_status'].value_counts()

smoking_status
never smoked       1892
Unknown            1544
formerly smoked     885
smokes              789
Name: count, dtype: int64

In [55]:
# Create a new variable called subset that contains only the age and stroke columns from the original DataFrame.
subset = df[['age','stroke']]
subset

       age  stroke
0     67.0       1
1     61.0       1
2     80.0       1
3     49.0       1
4     79.0       1
...    ...     ...
5105  80.0       0
5106  81.0       0
5107  35.0       0
5108  51.0       0
5109  44.0       0

[5110 rows x 2 columns]

# **Set 2 (Questions 11-20)**
Filtering, Sorting, and Column Operations

In [56]:
# Filter the DataFrame to show only the records where the age is 65 or older.
df[df['age'] >= 65]

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
5,56669,Male,81.0,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1
6,53882,Male,74.0,1,1,Yes,Private,Rural,70.09,27.4,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5092,56799,Male,76.0,0,0,Yes,Govt_job,Urban,82.35,38.9,never smoked,0
5097,64520,Male,68.0,0,0,Yes,Self-employed,Urban,91.68,40.8,Unknown,0
5100,68398,Male,82.0,1,0,Yes,Self-employed,Rural,71.97,28.3,never smoked,0
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0

In [57]:
# Find the average (mean) bmi of the individuals in the dataset.
df['bmi'].mean()

np.float64(28.893236911794666)

In [58]:
# Sort the entire DataFrame by avg_glucose_level in descending order (highest values first).
df.sort_values('avg_glucose_level',ascending=False)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
193,69112,Male,68.0,1,1,Yes,Private,Rural,271.74,31.1,smokes,1
1207,22440,Female,49.0,0,0,Yes,Private,Urban,267.76,29.3,formerly smoked,0
3088,26267,Female,76.0,0,0,Yes,Self-employed,Urban,267.61,27.9,smokes,0
4983,10995,Male,76.0,1,0,Yes,Private,Rural,267.60,30.5,never smoked,0
2462,27626,Female,60.0,0,0,No,Govt_job,Rural,266.59,25.5,never smoked,0
...,...,...,...,...,...,...,...,...,...,...,...,...
772,72547,Male,61.0,0,0,Yes,Private,Rural,55.26,33.2,Unknown,0
682,61300,Male,20.0,0,0,No,Private,Urban,55.25,20.4,never smoked,0
4110,43028,Male,66.0,0,0,Yes,Self-employed,Rural,55.23,28.9,Unknown,0
1191,37404,Male,42.0,0,0,Yes,Private,Urban,55.22,27.0,never smoked,0
4886,60562,Female,21.0,0,0,No,Private,Rural,55.12,21.8,never smoked,0

In [59]:
# Rename the column Residence_type to residence_area.
df.rename(columns={'Residence_type':'residence_area'},inplace=True)
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,residence_area,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [60]:
# Create a new column called age_in_months by multiplying the age column by 12.
df['age_in_months'] = df['age'] * 12
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,residence_area,avg_glucose_level,bmi,smoking_status,stroke,age_in_months
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1,804.0
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1,732.0
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1,960.0
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1,588.0
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1,948.0

In [61]:
# How many people in this dataset have had a stroke (where stroke == 1)?
strokeone = df['stroke'] == 1
strokeone.sum()

np.int64(249)

In [62]:
# Drop the id column from the DataFrame permanently (inplace or by reassigning).
df.drop('id',axis=1,inplace=True)

In [63]:
# Filter the dataset to show only "Female" patients who also have "hypertension".
df[(df['gender'] == 'Female') & (df['hypertension'] == 1)]

,gender,age,hypertension,heart_disease,ever_married,work_type,residence_area,avg_glucose_level,bmi,smoking_status,stroke,age_in_months
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1,948.0
10,Female,81.0,1,0,Yes,Private,Rural,80.43,29.7,never smoked,1,972.0
15,Female,50.0,1,0,Yes,Self-employed,Rural,167.41,30.9,never smoked,1,600.0
21,Female,52.0,1,0,Yes,Self-employed,Urban,233.29,48.9,never smoked,1,624.0
32,Female,82.0,1,0,Yes,Self-employed,Urban,196.92,22.2,never smoked,1,984.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4937,Female,62.0,1,0,Yes,Self-employed,Urban,103.69,35.2,smokes,0,744.0
4941,Female,51.0,1,0,Yes,Self-employed,Rural,176.34,28.4,never smoked,0,612.0
5088,Female,64.0,1,0,Yes,Self-employed,Urban,76.89,30.2,Unknown,0,768.0
5093,Female,45.0,1,0,Yes,Govt_job,Rural,95.02,NaN,smokes,0,540.0
5105,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0,960.0

In [64]:
# What is the maximum value in the bmi column?
df['bmi'].max()

97.6

In [65]:
# Check for null values again, but this time, calculate the percentage of missing values in each column rather than just the count.
(df.isna().sum() / len(df)) * 100

gender               0.000000
age                  0.000000
hypertension         0.000000
heart_disease        0.000000
ever_married         0.000000
work_type            0.000000
residence_area       0.000000
avg_glucose_level    0.000000
bmi                  3.933464
smoking_status       0.000000
stroke               0.000000
age_in_months        0.000000
dtype: float64

# **Set 3 (Questions 21-30)**
**Advanced Filtering & Logic**

In [66]:
# Sort the DataFrame first by gender (ascending) and then by age (descending) in a single command.
df.sort_values(by=['gender','age'],ascending=[True,False])

,gender,age,hypertension,heart_disease,ever_married,work_type,residence_area,avg_glucose_level,bmi,smoking_status,stroke,age_in_months
32,Female,82.00,1,0,Yes,Self-employed,Urban,196.92,22.2,never smoked,1,984.00
35,Female,82.00,1,1,No,Private,Rural,84.03,26.5,formerly smoked,1,984.00
56,Female,82.00,0,0,Yes,Private,Rural,59.32,33.2,never smoked,1,984.00
187,Female,82.00,1,1,Yes,Govt_job,Urban,215.94,27.9,formerly smoked,1,984.00
337,Female,82.00,0,1,No,Private,Urban,215.60,24.9,never smoked,0,984.00
...,...,...,...,...,...,...,...,...,...,...,...,...
3618,Male,0.16,0,0,No,children,Urban,114.71,17.4,Unknown,0,1.92
3968,Male,0.16,0,0,No,children,Rural,69.79,13.0,Unknown,0,1.92
4021,Male,0.16,0,0,No,children,Urban,109.52,13.9,Unknown,0,1.92
3295,Male,0.08,0,0,No,children,Rural,70.33,16.9,Unknown,0,0.96
3116,Other,26.00,0,0,No,Private,Rural,143.33,22.4,formerly smoked,0,312.00

In [67]:
# Use the .rename() method to change bmi to Body_Mass_Index and stroke to Stroke_Result simultaneously.
df.rename(columns={'bmi':'Body_Mass_Index','stroke':'Stroke_Result'},inplace=True)

In [81]:
# Calculate the percentage of the total population that is "Male".
perc = ((df['gender']=='Male').sum()) / (df.shape[0]) * 100
perc

np.float64(41.3894324853229)

In [90]:
# Filter the data to find patients who are "Private" workers AND have an avg_glucose_level greater than 200.
df[(df['work_type']=='Private') & (df['avg_glucose_level']>200)]

,gender,age,hypertension,heart_disease,ever_married,work_type,residence_area,avg_glucose_level,Body_Mass_Index,smoking_status,Stroke_Result,age_in_months
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1,804.0
13,Male,78.0,0,1,Yes,Private,Urban,219.84,NaN,Unknown,1,936.0
14,Female,79.0,0,1,Yes,Private,Urban,214.09,28.2,never smoked,1,948.0
17,Male,75.0,1,0,Yes,Private,Urban,221.29,25.8,smokes,1,900.0
23,Male,82.0,0,1,Yes,Private,Rural,208.30,32.5,Unknown,1,984.0
...,...,...,...,...,...,...,...,...,...,...,...,...
5001,Female,70.0,0,0,Yes,Private,Rural,212.87,34.8,never smoked,0,840.0
5029,Female,72.0,0,0,Yes,Private,Urban,206.49,26.3,never smoked,0,864.0
5034,Female,79.0,0,0,No,Private,Urban,253.86,28.8,formerly smoked,0,948.0
5035,Female,78.0,0,0,Yes,Private,Urban,203.36,28.7,formerly smoked,0,936.0
5061,Male,41.0,0,0,Yes,Private,Urban,223.78,32.3,never smoked,0,492.0

In [93]:
# Find the average age of people who have had a stroke vs. those who haven't (Use groupby).
df.groupby('Stroke_Result')['age'].mean()

Stroke_Result
0    41.971545
1    67.728193
Name: age, dtype: float64

In [124]:
# Create a column named is_obese which is True if bmi is greater than 30, and False otherwise.
df['is_obese'] = df['Body_Mass_Index'] > 30
df.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,residence_area,avg_glucose_level,Body_Mass_Index,smoking_status,Stroke_Result,age_in_months,is_obese
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1,804.0,True
1,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1,732.0,False
2,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1,960.0,True
3,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1,588.0,True
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1,948.0,False

In [110]:
# Count how many unique values exist in the work_type column.
df['work_type'].nunique()

5

In [122]:
# Retrieve the 5th to 15th rows of the DataFrame using .iloc.
df.iloc[4:15]

,gender,age,hypertension,heart_disease,ever_married,work_type,residence_area,avg_glucose_level,Body_Mass_Index,smoking_status,Stroke_Result,age_in_months
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1,948.0
5,Male,81.0,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1,972.0
6,Male,74.0,1,1,Yes,Private,Rural,70.09,27.4,never smoked,1,888.0
7,Female,69.0,0,0,No,Private,Urban,94.39,22.8,never smoked,1,828.0
8,Female,59.0,0,0,Yes,Private,Rural,76.15,NaN,Unknown,1,708.0
9,Female,78.0,0,0,Yes,Private,Urban,58.57,24.2,Unknown,1,936.0
10,Female,81.0,1,0,Yes,Private,Rural,80.43,29.7,never smoked,1,972.0
11,Female,61.0,0,1,Yes,Govt_job,Rural,120.46,36.8,smokes,1,732.0
12,Female,54.0,0,0,Yes,Private,Urban,104.51,27.3,smokes,1,648.0
13,Male,78.0,0,1,Yes,Private,Urban,219.84,NaN,Unknown,1,936.0
14,Female,79.0,0,1,Yes,Private,Urban,214.09,28.2,never smoked,1,948.0

In [115]:
# Filter for patients who are either "formerly smoked" or "smokes". (Hint: try using .isin()).
df[df['smoking_status'].isin(['formerly smoked','smokes'])]

,gender,age,hypertension,heart_disease,ever_married,work_type,residence_area,avg_glucose_level,Body_Mass_Index,smoking_status,Stroke_Result,age_in_months
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1,804.0
3,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1,588.0
5,Male,81.0,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1,972.0
11,Female,61.0,0,1,Yes,Govt_job,Rural,120.46,36.8,smokes,1,732.0
12,Female,54.0,0,0,Yes,Private,Urban,104.51,27.3,smokes,1,648.0
...,...,...,...,...,...,...,...,...,...,...,...,...
5087,Female,63.0,0,0,Yes,Self-employed,Rural,75.93,34.7,formerly smoked,0,756.0
5090,Male,26.0,0,0,No,Govt_job,Rural,100.85,21.0,smokes,0,312.0
5093,Female,45.0,1,0,Yes,Govt_job,Rural,95.02,NaN,smokes,0,540.0
5099,Male,40.0,0,0,Yes,Private,Rural,83.94,NaN,smokes,0,480.0
5108,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0,612.0

In [126]:
# Fill all the missing values in the bmi column with the median value of that column.
df['Body_Mass_Index'].fillna(value=df['Body_Mass_Index'].median(),inplace=True)
df

/tmp/ipython-input-3132492813.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Body_Mass_Index'].fillna(value=df['Body_Mass_Index'].median(),inplace=True)

,gender,age,hypertension,heart_disease,ever_married,work_type,residence_area,avg_glucose_level,Body_Mass_Index,smoking_status,Stroke_Result,age_in_months,is_obese
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1,804.0,True
1,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,28.1,never smoked,1,732.0,False
2,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1,960.0,True
3,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1,588.0,True
4,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1,948.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,Female,80.0,1,0,Yes,Private,Urban,83.75,28.1,never smoked,0,960.0,False
5106,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0,972.0,True
5107,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0,420.0,True
5108,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0,612.0,False
5109,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0,528.0,False