<a href="https://colab.research.google.com/github/Divyanshucode93/GoogleColabsPractice/blob/main/movies_Practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('/content/movies_fixed_utf8.csv', sep=';')

In [3]:
# Load the dataset and display the first 10 rows to get a feel for the data.
df.head(10)

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000,46998772.0,Warner Bros.,146.0
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000,58853106.0,Columbia Pictures,104.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067.0,Lucasfilm,124.0
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000,83453539.0,Paramount Pictures,88.0
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000,39846344.0,Orion Pictures,98.0
5,Friday the 13th,R,Horror,1980,"May 9, 1980 (United States)",6.4,123000.0,Sean S. Cunningham,Victor Miller,Betsy Palmer,United States,550000,39754601.0,Paramount Pictures,95.0
6,The Blues Brothers,R,Action,1980,"June 20, 1980 (United States)",7.9,188000.0,John Landis,Dan Aykroyd,John Belushi,United States,27000000,115229890.0,Universal Pictures,133.0
7,Raging Bull,R,Biography,1980,"December 19, 1980 (United States)",8.2,330000.0,Martin Scorsese,Jake LaMotta,Robert De Niro,United States,18000000,23402427.0,Chartoff-Winkler Productions,129.0
8,Superman II,PG,Action,1980,"June 19, 1981 (United States)",6.8,101000.0,Richard Lester,Jerry Siegel,Gene Hackman,United States,54000000,108185706.0,Dovemead Films,127.0
9,The Long Riders,R,Biography,1980,"May 16, 1980 (United States)",7.0,10000.0,Walter Hill,Bill Bryden,David Carradine,United States,10000000,15795189.0,United Artists,100.0

In [4]:
# Find the total number of rows and columns in the DataFrame.
df.shape

(4000, 15)

In [5]:
# Create a new DataFrame containing only the columns: name, genre, and score. Display the first 5 rows of this new DataFrame.
temp_df = df[['name', 'genre', 'score']]
temp_df.head(5)

                                             name      genre  score
0                                     The Shining      Drama    8.4
1                                 The Blue Lagoon  Adventure    5.8
2  Star Wars: Episode V - The Empire Strikes Back     Action    8.7
3                                       Airplane!     Comedy    7.7
4                                      Caddyshack     Comedy    7.3

In [6]:
# How many unique genres are there in this dataset? List them.
df['genre'].value_counts()

genre
Comedy       1355
Drama         807
Action        775
Crime         302
Adventure     231
Biography     175
Horror        158
Animation     113
Fantasy        33
Mystery        13
Thriller       11
Family          8
Romance         8
Sci-Fi          6
Western         3
Music           1
History         1
Name: count, dtype: int64

In [7]:
# Filter the dataset to find all movies that have a score greater than 8.5.
df[df['score'] > 8.5]

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067.0,Lucasfilm,124.0
1643,Goodfellas,R,Biography,1990,"September 21, 1990 (United States)",8.7,1100000.0,Martin Scorsese,Nicholas Pileggi,Robert De Niro,United States,25000000,46963277.0,Warner Bros.,146.0
1845,The Silence of the Lambs,R,Crime,1991,"February 14, 1991 (United States)",8.6,1300000.0,Jonathan Demme,Thomas Harris,Jodie Foster,United States,19000000,272742922.0,Strong Heart/Demme Production,118.0
2247,Schindler's List,R,Biography,1993,"February 4, 1994 (United States)",8.9,1200000.0,Steven Spielberg,Thomas Keneally,Liam Neeson,United States,22000000,322161245.0,Universal Pictures,195.0
2443,The Shawshank Redemption,R,Drama,1994,"October 14, 1994 (United States)",9.3,2400000.0,Frank Darabont,Stephen King,Tim Robbins,United States,25000000,28817291.0,Castle Rock Entertainment,142.0
2444,Pulp Fiction,R,Crime,1994,"October 14, 1994 (United States)",8.9,1900000.0,Quentin Tarantino,Quentin Tarantino,John Travolta,United States,8000000,213928762.0,Miramax,154.0
2445,Forrest Gump,PG-13,Drama,1994,"July 6, 1994 (United States)",8.8,1900000.0,Robert Zemeckis,Winston Groom,Tom Hanks,United States,55000000,678226133.0,Paramount Pictures,142.0
2645,Se7en,R,Crime,1995,"September 22, 1995 (United States)",8.6,1500000.0,David Fincher,Andrew Kevin Walker,Morgan Freeman,United States,33000000,327333559.0,Cecchi Gori Pictures,127.0
3055,Life Is Beautiful,PG-13,Comedy,1997,"December 20, 1997 (Italy)",8.6,642000.0,Roberto Benigni,Vincenzo Cerami,Roberto Benigni,Italy,20000000,230098753.0,Melampo Cinematografica,116.0
3244,Saving Private Ryan,R,Drama,1998,"July 24, 1998 (United States)",8.6,1300000.0,Steven Spielberg,Robert Rodat,Tom Hanks,United States,70000000,482349603.0,Dreamworks Pictures,169.0
3443,The Matrix,R,Action,1999,"March 31, 1999 (United States)",8.7,1700000.0,Lana Wachowski,Lilly Wachowski,Keanu Reeves,United States,63000000,466364845.0,Warner Bros.,136.0
3444,Fight Club,R,Drama,1999,"October 15, 1999 (United States)",8.8,1900000.0,David Fincher,Chuck Palahniuk,Brad Pitt,Germany,63000000,101209702.0,Fox 2000 Pictures,139.0
3449,The Green Mile,R,Crime,1999,"December 10, 1999 (United States)",8.6,1200000.0,Frank Darabont,Stephen King,Tom Hanks,United States,60000000,286801374.0,Castle Rock Entertainment,189.0
3845,The Lord of the Rings: The Fellowship of the Ring,PG-13,Action,2001,"December 19, 2001 (United States)",8.8,1700000.0,Peter Jackson,J.R.R. Tolkien,Elijah Wood,New Zealand,93000000,897690072.0,New Line Cinema,178.0
3849,Spirited Away,PG,Animation,2001,"March 28, 2003 (United States)",8.6,679000.0,Hayao Miyazaki,Hayao Miyazaki,Daveigh Chase,Japan,19000000,355475245.0,Tokuma Shoten,125.0

In [8]:
# Sort the movies by their year of release in descending order (newest first) and show the top 5 results.
df.sort_values('year', ascending=False).head(5)

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
3970,Hearts in Atlantis,PG-13,Drama,2001,"September 28, 2001 (United States)",6.9,37000.0,Scott Hicks,Stephen King,Anthony Hopkins,United States,31000000,30919415.0,Castle Rock Entertainment,101.0
3984,Iris,R,Biography,2001,"March 29, 2002 (United States)",7.0,18000.0,Richard Eyre,John Bayley,Judi Dench,United Kingdom,5500000,16153953.0,British Broadcasting Corporation (BBC),91.0
3983,15 Minutes,R,Action,2001,"March 9, 2001 (United States)",6.1,49000.0,John Herzfeld,John Herzfeld,Robert De Niro,United States,60000000,56359980.0,New Line Cinema,120.0
3982,Formula 51,R,Action,2001,"October 18, 2002 (United States)",6.3,48000.0,Ronny Yu,Stel Pavlou,Samuel L. Jackson,United Kingdom,27000000,12881605.0,Alliance Atlantis Communications,93.0
3981,The Tailor of Panama,R,Comedy,2001,"March 30, 2001 (United States)",6.2,28000.0,John Boorman,John le Carré,Pierce Brosnan,United States,21000000,28008462.0,Columbia Pictures,109.0

In [9]:
# Check how many missing (NaN) values are present in the gross column.
df['gross'].isna().sum()

np.int64(169)

In [10]:
# Display all movies where the director is 'Christopher Nolan' (if any) or 'Steven Spielberg'.
df[(df['director'] == 'Christopher Nolan') | (df['director'] == 'Steven Spielberg')]

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
92,Indiana Jones and the Raiders of the Lost Ark,PG,Action,1981,"June 12, 1981 (United States)",8.4,905000.0,Steven Spielberg,Lawrence Kasdan,Harrison Ford,United States,18000000,3.899260e+08,Paramount Pictures,115.0
209,E.T. the Extra-Terrestrial,PG,Family,1982,"June 11, 1982 (United States)",7.8,381000.0,Steven Spielberg,Melissa Mathison,Henry Thomas,United States,10500000,7.929106e+08,Universal Pictures,115.0
481,Indiana Jones and the Temple of Doom,PG,Action,1984,"May 23, 1984 (United States)",7.5,459000.0,Steven Spielberg,Willard Huyck,Harrison Ford,United States,28000000,3.331073e+08,Paramount Pictures,118.0
661,The Color Purple,PG-13,Drama,1985,"February 7, 1986 (United States)",7.8,81000.0,Steven Spielberg,Menno Meyjes,Danny Glover,United States,15000000,9.846786e+07,Amblin Entertainment,154.0
1059,Empire of the Sun,PG,Action,1987,"December 25, 1987 (United States)",7.7,119000.0,Steven Spielberg,Tom Stoppard,Christian Bale,United States,35000000,2.223870e+07,Amblin Entertainment,153.0
1443,Indiana Jones and the Last Crusade,PG-13,Action,1989,"May 24, 1989 (United States)",8.2,707000.0,Steven Spielberg,Jeffrey Boam,Harrison Ford,United States,48000000,4.741718e+08,Paramount Pictures,127.0
1492,Always,PG,Drama,1989,"December 22, 1989 (United States)",6.4,29000.0,Steven Spielberg,Jerry Belson,Richard Dreyfuss,United States,31000000,7.413479e+07,Universal Pictures,122.0
1846,Hook,PG,Adventure,1991,"December 11, 1991 (United States)",6.8,240000.0,Steven Spielberg,J.M. Barrie,Dustin Hoffman,United States,70000000,3.008548e+08,Amblin Entertainment,142.0
2245,Jurassic Park,PG-13,Action,1993,"June 11, 1993 (United States)",8.1,894000.0,Steven Spielberg,Michael Crichton,Sam Neill,United States,63000000,1.033928e+09,Universal Pictures,127.0
2247,Schindler's List,R,Biography,1993,"February 4, 1994 (United States)",8.9,1200000.0,Steven Spielberg,Thomas Keneally,Liam Neeson,United States,22000000,3.221612e+08,Universal Pictures,195.0
3064,The Lost World: Jurassic Park,PG-13,Action,1997,"May 23, 1997 (United States)",6.6,388000.0,Steven Spielberg,Michael Crichton,Jeff Goldblum,United States,73000000,6.186390e+08,Universal Pictures,129.0
3106,Amistad,R,Biography,1997,"December 25, 1997 (United States)",7.3,73000.0,Steven Spielberg,David Franzoni,Djimon Hounsou,United States,36000000,4.422944e+07,Dreamworks Pictures,155.0
3244,Saving Private Ryan,R,Drama,1998,"July 24, 1998 (United States)",8.6,1300000.0,Steven Spielberg,Robert Rodat,Tom Hanks,United States,70000000,4.823496e+08,Dreamworks Pictures,169.0
3318,Following,R,Crime,1998,"November 5, 1999 (United Kingdom)",7.5,89000.0,Christopher Nolan,Christopher Nolan,Jeremy Theobald,United Kingdom,6000,4.848200e+04,Next Wave Films,69.0
3648,Memento,R,Mystery,2000,"May 25, 2001 (United States)",8.4,1200000.0,Christopher Nolan,Christopher Nolan,Guy Pearce,United States,9000000,4.004708e+07,Newmarket Capital Group,113.0
3862,A.I. Artificial Intelligence,PG-13,Drama,2001,"June 29, 2001 (United States)",7.2,295000.0,Steven Spielberg,Brian Aldiss,Haley Joel Osment,United States,100000000,2.359266e+08,Warner Bros.,146.0

In [11]:
# What is the average (mean) runtime of all the movies in the dataset?
df['runtime'].mean()

np.float64(105.71175)

In [12]:
# How many movies in this dataset were released in the year 1995?
df[df['year'] == 1995].shape[0]

200

In [13]:
##################################################################################################################################

In [14]:
# Create a new column called profit by subtracting budget from gross.
df['profit'] = df['gross'] - df['budget']
df

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,profit
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000,46998772.0,Warner Bros.,146.0,27998772.0
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000,58853106.0,Columbia Pictures,104.0,54353106.0
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067.0,Lucasfilm,124.0,520375067.0
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000,83453539.0,Paramount Pictures,88.0,79953539.0
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000,39846344.0,Orion Pictures,98.0,33846344.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,Birthday Girl,R,Comedy,2001,"February 1, 2002 (United States)",6.1,25000.0,Jez Butterworth,Tom Butterworth,Nicole Kidman,United Kingdom,13000000,16171098.0,FilmFour,93.0,3171098.0
3996,Human Nature,R,Comedy,2001,"September 12, 2001 (France)",6.4,18000.0,Michel Gondry,Charlie Kaufman,Tim Robbins,France,0,1574660.0,Fine Line Features,96.0,1574660.0
3997,Made,R,Comedy,2001,"August 31, 2001 (United States)",6.4,18000.0,Jon Favreau,Jon Favreau,Vince Vaughn,United States,5000000,5480653.0,Artisan Entertainment,95.0,480653.0
3998,One Night at McCool's,R,Comedy,2001,"April 27, 2001 (United States)",6.1,29000.0,Harald Zwart,Stan Seidel,Liv Tyler,United States,18000000,13578186.0,October Films,93.0,-4421814.0
3999,Dr. Dolittle 2,PG,Comedy,2001,"June 22, 2001 (United States)",4.7,42000.0,Steve Carr,Hugh Lofting,Eddie Murphy,United States,70000000,176104344.0,Twentieth Century Fox,87.0,106104344.0

In [15]:
# Using the profit column you just created, find the top 3 most profitable movies.
df.sort_values('profit', ascending=False).head(3)

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,profit
3045,Titanic,PG-13,Drama,1997,"December 19, 1997 (United States)",7.8,1100000.0,James Cameron,James Cameron,Leonardo DiCaprio,United States,200000000,2.201647e+09,Twentieth Century Fox,194.0,2.001647e+09
2448,The Lion King,G,Animation,1994,"June 24, 1994 (United States)",8.5,970000.0,Roger Allers,Irene Mecchi,Matthew Broderick,United States,45000000,1.083721e+09,Walt Disney Pictures,88.0,1.038721e+09
2245,Jurassic Park,PG-13,Action,1993,"June 11, 1993 (United States)",8.1,894000.0,Steven Spielberg,Michael Crichton,Sam Neill,United States,63000000,1.033928e+09,Universal Pictures,127.0,9.709283e+08

In [16]:
# What is the average budget and average score for each genre?
df.groupby('genre')[['budget', 'score']].mean()

                 budget     score
genre
Action     2.662222e+07  6.014968
Adventure  1.906866e+07  6.151948
Animation  2.978496e+07  6.883186
Biography  1.415731e+07  7.052000
Comedy     1.109598e+07  6.179410
Crime      1.440766e+07  6.645033
Drama      1.134991e+07  6.673606
Family     3.687500e+06  6.550000
Fantasy    1.665758e+07  6.024242
History    3.235620e+05  8.300000
Horror     8.318525e+06  5.744304
Music      0.000000e+00  7.200000
Mystery    1.791538e+07  6.500000
Romance    5.625000e+06  6.400000
Sci-Fi     8.416667e+06  5.983333
Thriller   3.681818e+06  5.890909
Western    7.000000e+06  5.666667

In [17]:
# Find all movies in the 'Action' genre that have a score higher than 8.0 and were released after the year 2000.
df[(df['genre'] == 'Action') & (df['score'] > 8.0) & (df['year'] > 2000)]

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,profit
3845,The Lord of the Rings: The Fellowship of the Ring,PG-13,Action,2001,"December 19, 2001 (United States)",8.8,1700000.0,Peter Jackson,J.R.R. Tolkien,Elijah Wood,New Zealand,93000000,897690072.0,New Line Cinema,178.0,804690072.0

In [18]:
# The released column contains the date and the country (e.g., "June 13, 1980 (United States)"). Create a new column release_country that contains only the country name inside the parentheses.
df['release_country'] = df['released'].str.strip().str.split(' ',n=3).str.get(3).str.strip()
df

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,profit,release_country
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000,46998772.0,Warner Bros.,146.0,27998772.0,(United States)
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000,58853106.0,Columbia Pictures,104.0,54353106.0,(United States)
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067.0,Lucasfilm,124.0,520375067.0,(United States)
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000,83453539.0,Paramount Pictures,88.0,79953539.0,(United States)
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000,39846344.0,Orion Pictures,98.0,33846344.0,(United States)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,Birthday Girl,R,Comedy,2001,"February 1, 2002 (United States)",6.1,25000.0,Jez Butterworth,Tom Butterworth,Nicole Kidman,United Kingdom,13000000,16171098.0,FilmFour,93.0,3171098.0,(United States)
3996,Human Nature,R,Comedy,2001,"September 12, 2001 (France)",6.4,18000.0,Michel Gondry,Charlie Kaufman,Tim Robbins,France,0,1574660.0,Fine Line Features,96.0,1574660.0,(France)
3997,Made,R,Comedy,2001,"August 31, 2001 (United States)",6.4,18000.0,Jon Favreau,Jon Favreau,Vince Vaughn,United States,5000000,5480653.0,Artisan Entertainment,95.0,480653.0,(United States)
3998,One Night at McCool's,R,Comedy,2001,"April 27, 2001 (United States)",6.1,29000.0,Harald Zwart,Stan Seidel,Liv Tyler,United States,18000000,13578186.0,October Films,93.0,-4421814.0,(United States)
3999,Dr. Dolittle 2,PG,Comedy,2001,"June 22, 2001 (United States)",4.7,42000.0,Steve Carr,Hugh Lofting,Eddie Murphy,United States,70000000,176104344.0,Twentieth Century Fox,87.0,106104344.0,(United States)

In [19]:
# How many movies made a gross amount that was less than their budget? (These are the movies that "lost" money).
df[df['gross'] < df['budget']].shape[0]

1069

In [20]:
# Create a pivot table showing the median score for each rating across different genres.
df.pivot_table(index='genre', columns='rating', values='score', aggfunc='median')

rating,Approved,G,NC-17,Not Rated,PG,PG-13,R,TV-MA,TV-PG,Unrated,X
genre,,,,,,,,,,,
Action,NaN,7.00,NaN,6.95,5.70,6.10,6.10,NaN,NaN,NaN,NaN
Adventure,3.4,5.95,NaN,6.45,6.20,6.35,6.40,NaN,NaN,NaN,NaN
Animation,NaN,6.90,NaN,7.25,6.90,6.10,7.70,8.0,NaN,NaN,NaN
Biography,NaN,8.00,6.3,7.40,7.20,7.00,7.20,6.9,NaN,7.15,NaN
Comedy,NaN,6.95,7.0,7.50,6.05,6.10,6.40,NaN,5.1,6.45,NaN
Crime,NaN,NaN,7.1,7.40,6.50,7.20,6.50,NaN,NaN,6.65,7.6
Drama,NaN,7.30,6.2,7.20,6.80,6.70,6.60,7.0,6.6,7.25,5.8
Family,NaN,6.50,NaN,NaN,6.30,NaN,NaN,NaN,NaN,NaN,NaN
Fantasy,NaN,NaN,NaN,NaN,5.50,5.70,6.20,NaN,NaN,NaN,NaN
Horror,NaN,NaN,7.5,6.60,5.50,5.15,5.80,NaN,NaN,NaN,7.3
Music,NaN,NaN,NaN,NaN,NaN,NaN,7.20,NaN,NaN,NaN,NaN
Mystery,NaN,NaN,NaN,NaN,NaN,5.60,6.70,NaN,NaN,NaN,NaN
Romance,NaN,NaN,NaN,7.80,7.00,NaN,5.65,NaN,NaN,NaN,NaN
Sci-Fi,NaN,NaN,NaN,5.80,5.85,6.20,6.10,NaN,NaN,NaN,NaN
Thriller,NaN,NaN,NaN,NaN,6.20,NaN,5.90,NaN,NaN,NaN,NaN
Western,NaN,NaN,NaN,NaN,6.40,NaN,5.30,NaN,NaN,NaN,NaN

In [21]:
# There are some rows where budget or gross might be 0 (often used as a placeholder for missing data). Calculate the mean gross excluding the rows where gross is 0 or NaN.
df[df['gross']>0]['gross'].mean()

np.float64(41722023.000522055)

In [22]:
########################################################################################################################################

In [23]:
# The released column is currently a string. Create a new column release_date that is a proper datetime object. (Hint: You'll need to strip the country name first. You can use .str.replace or regex to remove everything from the first ( to the end).
df['release_date'] = df['released'].str.split('(').str.get(0).str.strip()
df

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,profit,release_country,release_date
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000,46998772.0,Warner Bros.,146.0,27998772.0,(United States),"June 13, 1980"
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000,58853106.0,Columbia Pictures,104.0,54353106.0,(United States),"July 2, 1980"
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067.0,Lucasfilm,124.0,520375067.0,(United States),"June 20, 1980"
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000,83453539.0,Paramount Pictures,88.0,79953539.0,(United States),"July 2, 1980"
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000,39846344.0,Orion Pictures,98.0,33846344.0,(United States),"July 25, 1980"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,Birthday Girl,R,Comedy,2001,"February 1, 2002 (United States)",6.1,25000.0,Jez Butterworth,Tom Butterworth,Nicole Kidman,United Kingdom,13000000,16171098.0,FilmFour,93.0,3171098.0,(United States),"February 1, 2002"
3996,Human Nature,R,Comedy,2001,"September 12, 2001 (France)",6.4,18000.0,Michel Gondry,Charlie Kaufman,Tim Robbins,France,0,1574660.0,Fine Line Features,96.0,1574660.0,(France),"September 12, 2001"
3997,Made,R,Comedy,2001,"August 31, 2001 (United States)",6.4,18000.0,Jon Favreau,Jon Favreau,Vince Vaughn,United States,5000000,5480653.0,Artisan Entertainment,95.0,480653.0,(United States),"August 31, 2001"
3998,One Night at McCool's,R,Comedy,2001,"April 27, 2001 (United States)",6.1,29000.0,Harald Zwart,Stan Seidel,Liv Tyler,United States,18000000,13578186.0,October Films,93.0,-4421814.0,(United States),"April 27, 2001"
3999,Dr. Dolittle 2,PG,Comedy,2001,"June 22, 2001 (United States)",4.7,42000.0,Steve Carr,Hugh Lofting,Eddie Murphy,United States,70000000,176104344.0,Twentieth Century Fox,87.0,106104344.0,(United States),"June 22, 2001"

In [24]:
# We noticed 1392 movies have a budget of 0. This is bad for analysis. Replace those 0 values with the median budget of their respective genre. (Hint: Use groupby + transform).
df.groupby('genre')['budget'].fillna(value=df.groupby('genre')['budget'].median())

/tmp/ipython-input-2965262400.py:2: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
  df.groupby('genre')['budget'].fillna(value=df.groupby('genre')['budget'].median())

0       19000000
1        4500000
2       18000000
3        3500000
4        6000000
          ...
3995    13000000
3996           0
3997     5000000
3998    18000000
3999    70000000
Name: budget, Length: 4000, dtype: int64

In [25]:
# Create a new categorical column score_category where:
# Score < 5.0 --> 'Low'
# 5.0 <= Score < 7.5 --> 'Medium'
# Score >= 7.5 --> 'High'
def scorecat(val):
  if val < 5.0:
    return 'Low'
  elif (val >= 5.0) & (val < 7.5):
    return 'Medium'
  else:
    return 'High'

df['score_category'] = df['score'].apply(scorecat)
df

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,profit,release_country,release_date,score_category
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000,46998772.0,Warner Bros.,146.0,27998772.0,(United States),"June 13, 1980",High
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000,58853106.0,Columbia Pictures,104.0,54353106.0,(United States),"July 2, 1980",Medium
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067.0,Lucasfilm,124.0,520375067.0,(United States),"June 20, 1980",High
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000,83453539.0,Paramount Pictures,88.0,79953539.0,(United States),"July 2, 1980",High
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000,39846344.0,Orion Pictures,98.0,33846344.0,(United States),"July 25, 1980",Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,Birthday Girl,R,Comedy,2001,"February 1, 2002 (United States)",6.1,25000.0,Jez Butterworth,Tom Butterworth,Nicole Kidman,United Kingdom,13000000,16171098.0,FilmFour,93.0,3171098.0,(United States),"February 1, 2002",Medium
3996,Human Nature,R,Comedy,2001,"September 12, 2001 (France)",6.4,18000.0,Michel Gondry,Charlie Kaufman,Tim Robbins,France,0,1574660.0,Fine Line Features,96.0,1574660.0,(France),"September 12, 2001",Medium
3997,Made,R,Comedy,2001,"August 31, 2001 (United States)",6.4,18000.0,Jon Favreau,Jon Favreau,Vince Vaughn,United States,5000000,5480653.0,Artisan Entertainment,95.0,480653.0,(United States),"August 31, 2001",Medium
3998,One Night at McCool's,R,Comedy,2001,"April 27, 2001 (United States)",6.1,29000.0,Harald Zwart,Stan Seidel,Liv Tyler,United States,18000000,13578186.0,October Films,93.0,-4421814.0,(United States),"April 27, 2001",Medium
3999,Dr. Dolittle 2,PG,Comedy,2001,"June 22, 2001 (United States)",4.7,42000.0,Steve Carr,Hugh Lofting,Eddie Murphy,United States,70000000,176104344.0,Twentieth Century Fox,87.0,106104344.0,(United States),"June 22, 2001",Low

In [26]:
# Find the top 5 director and star combinations that have the highest average score, but only include pairs that have made at least 3 movies together.
duos = df.groupby(['director', 'star'])['score'].agg(['mean', 'count'])
top_duos = duos[duos['count'] >= 3].sort_values('mean', ascending=False).head(5)
top_duos

                                            mean  count
director         star
Martin Scorsese  Robert De Niro         8.040000      5
Steven Spielberg Harrison Ford          8.033333      3
Robert Zemeckis  Michael J. Fox         7.900000      3
James Cameron    Arnold Schwarzenegger  7.900000      3
Jim Sheridan     Daniel Day-Lewis       7.666667      3

In [27]:
# Using the release_date column you created in Q1, find which month of the year (January-December) has the highest average gross earnings.
df['release_date'] = pd.to_datetime(df['released'].str.split('(').str.get(0).str.strip(), errors='coerce')
df

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,profit,release_country,release_date,score_category
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000,46998772.0,Warner Bros.,146.0,27998772.0,(United States),1980-06-13,High
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000,58853106.0,Columbia Pictures,104.0,54353106.0,(United States),1980-07-02,Medium
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067.0,Lucasfilm,124.0,520375067.0,(United States),1980-06-20,High
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000,83453539.0,Paramount Pictures,88.0,79953539.0,(United States),1980-07-02,High
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000,39846344.0,Orion Pictures,98.0,33846344.0,(United States),1980-07-25,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,Birthday Girl,R,Comedy,2001,"February 1, 2002 (United States)",6.1,25000.0,Jez Butterworth,Tom Butterworth,Nicole Kidman,United Kingdom,13000000,16171098.0,FilmFour,93.0,3171098.0,(United States),2002-02-01,Medium
3996,Human Nature,R,Comedy,2001,"September 12, 2001 (France)",6.4,18000.0,Michel Gondry,Charlie Kaufman,Tim Robbins,France,0,1574660.0,Fine Line Features,96.0,1574660.0,(France),2001-09-12,Medium
3997,Made,R,Comedy,2001,"August 31, 2001 (United States)",6.4,18000.0,Jon Favreau,Jon Favreau,Vince Vaughn,United States,5000000,5480653.0,Artisan Entertainment,95.0,480653.0,(United States),2001-08-31,Medium
3998,One Night at McCool's,R,Comedy,2001,"April 27, 2001 (United States)",6.1,29000.0,Harald Zwart,Stan Seidel,Liv Tyler,United States,18000000,13578186.0,October Films,93.0,-4421814.0,(United States),2001-04-27,Medium
3999,Dr. Dolittle 2,PG,Comedy,2001,"June 22, 2001 (United States)",4.7,42000.0,Steve Carr,Hugh Lofting,Eddie Murphy,United States,70000000,176104344.0,Twentieth Century Fox,87.0,106104344.0,(United States),2001-06-22,Low

In [28]:
# Calculate what percentage of the total gross of the entire dataset is contributed by the top 5 companies.
total_gross = df['gross'].sum()
top_5_companies_gross = df.groupby('company')['gross'].sum().sort_values(ascending=False).head(5).sum()
perc = (top_5_companies_gross / total_gross) * 100
perc

np.float64(41.68172650316101)

In [29]:
# Calculate the Pearson correlation coefficient between budget, gross, and score. Which pair has the strongest relationship?

In [30]:
# Write a small function that classifies runtime into 'Short' (<90 mins), 'Standard' (90-130 mins), and 'Long' (>130 mins). Apply this function to create a new column duration_type.
def runtimeclass(val):
  if(val < 90):
    return 'Short'
  elif((val >= 90) & (val <= 130)):
    return 'Standard'
  else:
    return 'Long'

df['duration_type'] = df['runtime'].apply(runtimeclass)
df

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,profit,release_country,release_date,score_category,duration_type
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000,46998772.0,Warner Bros.,146.0,27998772.0,(United States),1980-06-13,High,Long
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000,58853106.0,Columbia Pictures,104.0,54353106.0,(United States),1980-07-02,Medium,Standard
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067.0,Lucasfilm,124.0,520375067.0,(United States),1980-06-20,High,Standard
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000,83453539.0,Paramount Pictures,88.0,79953539.0,(United States),1980-07-02,High,Short
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000,39846344.0,Orion Pictures,98.0,33846344.0,(United States),1980-07-25,Medium,Standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,Birthday Girl,R,Comedy,2001,"February 1, 2002 (United States)",6.1,25000.0,Jez Butterworth,Tom Butterworth,Nicole Kidman,United Kingdom,13000000,16171098.0,FilmFour,93.0,3171098.0,(United States),2002-02-01,Medium,Standard
3996,Human Nature,R,Comedy,2001,"September 12, 2001 (France)",6.4,18000.0,Michel Gondry,Charlie Kaufman,Tim Robbins,France,0,1574660.0,Fine Line Features,96.0,1574660.0,(France),2001-09-12,Medium,Standard
3997,Made,R,Comedy,2001,"August 31, 2001 (United States)",6.4,18000.0,Jon Favreau,Jon Favreau,Vince Vaughn,United States,5000000,5480653.0,Artisan Entertainment,95.0,480653.0,(United States),2001-08-31,Medium,Standard
3998,One Night at McCool's,R,Comedy,2001,"April 27, 2001 (United States)",6.1,29000.0,Harald Zwart,Stan Seidel,Liv Tyler,United States,18000000,13578186.0,October Films,93.0,-4421814.0,(United States),2001-04-27,Medium,Standard
3999,Dr. Dolittle 2,PG,Comedy,2001,"June 22, 2001 (United States)",4.7,42000.0,Steve Carr,Hugh Lofting,Eddie Murphy,United States,70000000,176104344.0,Twentieth Century Fox,87.0,106104344.0,(United States),2001-06-22,Low,Short

In [31]:
#######################################################################################################################################################

In [32]:
# Basic Aggregation: Group the movies by rating. Find the count of movies and the average score for each rating.
avg_count = df.groupby('rating')[['name','score']].agg({'name':'count','score':'mean'})
avg_count

           name     score
rating
Approved      1  3.400000
G           106  6.703774
NC-17        14  6.528571
Not Rated    92  7.144565
PG          815  6.174601
PG-13       848  6.189387
R          2043  6.356535
TV-MA         4  7.225000
TV-PG         2  5.850000
Unrated      32  6.793750
X             3  6.900000

In [33]:
# Named Aggregation: Perform the same operation as above, but name the resulting columns total_movies and average_movie_score.

# This creates a NEW summary DataFrame
rating_summary = df.groupby('rating').agg(
    total_movies=('name', 'count'),
    average_movie_score=('score', 'mean')
)
print(rating_summary)
df

           total_movies  average_movie_score
rating
Approved              1             3.400000
G                   106             6.703774
NC-17                14             6.528571
Not Rated            92             7.144565
PG                  815             6.174601
PG-13               848             6.189387
R                  2043             6.356535
TV-MA                 4             7.225000
TV-PG                 2             5.850000
Unrated              32             6.793750
X                     3             6.900000

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime,profit,release_country,release_date,score_category,duration_type
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000,46998772.0,Warner Bros.,146.0,27998772.0,(United States),1980-06-13,High,Long
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000,58853106.0,Columbia Pictures,104.0,54353106.0,(United States),1980-07-02,Medium,Standard
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067.0,Lucasfilm,124.0,520375067.0,(United States),1980-06-20,High,Standard
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000,83453539.0,Paramount Pictures,88.0,79953539.0,(United States),1980-07-02,High,Short
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000,39846344.0,Orion Pictures,98.0,33846344.0,(United States),1980-07-25,Medium,Standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,Birthday Girl,R,Comedy,2001,"February 1, 2002 (United States)",6.1,25000.0,Jez Butterworth,Tom Butterworth,Nicole Kidman,United Kingdom,13000000,16171098.0,FilmFour,93.0,3171098.0,(United States),2002-02-01,Medium,Standard
3996,Human Nature,R,Comedy,2001,"September 12, 2001 (France)",6.4,18000.0,Michel Gondry,Charlie Kaufman,Tim Robbins,France,0,1574660.0,Fine Line Features,96.0,1574660.0,(France),2001-09-12,Medium,Standard
3997,Made,R,Comedy,2001,"August 31, 2001 (United States)",6.4,18000.0,Jon Favreau,Jon Favreau,Vince Vaughn,United States,5000000,5480653.0,Artisan Entertainment,95.0,480653.0,(United States),2001-08-31,Medium,Standard
3998,One Night at McCool's,R,Comedy,2001,"April 27, 2001 (United States)",6.1,29000.0,Harald Zwart,Stan Seidel,Liv Tyler,United States,18000000,13578186.0,October Films,93.0,-4421814.0,(United States),2001-04-27,Medium,Standard
3999,Dr. Dolittle 2,PG,Comedy,2001,"June 22, 2001 (United States)",4.7,42000.0,Steve Carr,Hugh Lofting,Eddie Murphy,United States,70000000,176104344.0,Twentieth Century Fox,87.0,106104344.0,(United States),2001-06-22,Low,Short

In [34]:
# Handling Zeroes: Replace all 0 values in the budget column with NaN. Then, count how many NaN values are now in that column.

# You must assign it back to the column to "save" the NaNs
df['budget'] = df['budget'].replace(0, np.nan)

# Now you can count them
print(df['budget'].isna().sum())

1392

In [35]:
# Transform (Intermediate): Create a new column genre_avg_gross. This column should contain the mean gross of the genre that the movie belongs to. (Hint: Use groupby('genre')['gross'].transform('mean')).

# .transform() calculates the mean but keeps the original shape (4,000 rows)
df['genre_avg_gross'] = df.groupby('genre')['gross'].transform('mean')
df

,name,rating,genre,year,released,score,votes,director,writer,star,...,budget,gross,company,runtime,profit,release_country,release_date,score_category,duration_type,genre_avg_gross
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000.0,Stanley Kubrick,Stephen King,Jack Nicholson,...,19000000.0,46998772.0,Warner Bros.,146.0,27998772.0,(United States),1980-06-13,High,Long,3.089225e+07
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000.0,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,...,4500000.0,58853106.0,Columbia Pictures,104.0,54353106.0,(United States),1980-07-02,Medium,Standard,4.786276e+07
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000.0,Irvin Kershner,Leigh Brackett,Mark Hamill,...,18000000.0,538375067.0,Lucasfilm,124.0,520375067.0,(United States),1980-06-20,High,Standard,7.232715e+07
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000.0,Jim Abrahams,Jim Abrahams,Robert Hays,...,3500000.0,83453539.0,Paramount Pictures,88.0,79953539.0,(United States),1980-07-02,High,Short,3.108453e+07
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000.0,Harold Ramis,Brian Doyle-Murray,Chevy Chase,...,6000000.0,39846344.0,Orion Pictures,98.0,33846344.0,(United States),1980-07-25,Medium,Standard,3.108453e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,Birthday Girl,R,Comedy,2001,"February 1, 2002 (United States)",6.1,25000.0,Jez Butterworth,Tom Butterworth,Nicole Kidman,...,13000000.0,16171098.0,FilmFour,93.0,3171098.0,(United States),2002-02-01,Medium,Standard,3.108453e+07
3996,Human Nature,R,Comedy,2001,"September 12, 2001 (France)",6.4,18000.0,Michel Gondry,Charlie Kaufman,Tim Robbins,...,NaN,1574660.0,Fine Line Features,96.0,1574660.0,(France),2001-09-12,Medium,Standard,3.108453e+07
3997,Made,R,Comedy,2001,"August 31, 2001 (United States)",6.4,18000.0,Jon Favreau,Jon Favreau,Vince Vaughn,...,5000000.0,5480653.0,Artisan Entertainment,95.0,480653.0,(United States),2001-08-31,Medium,Standard,3.108453e+07
3998,One Night at McCool's,R,Comedy,2001,"April 27, 2001 (United States)",6.1,29000.0,Harald Zwart,Stan Seidel,Liv Tyler,...,18000000.0,13578186.0,October Films,93.0,-4421814.0,(United States),2001-04-27,Medium,Standard,3.108453e+07
3999,Dr. Dolittle 2,PG,Comedy,2001,"June 22, 2001 (United States)",4.7,42000.0,Steve Carr,Hugh Lofting,Eddie Murphy,...,70000000.0,176104344.0,Twentieth Century Fox,87.0,106104344.0,(United States),2001-06-22,Low,Short,3.108453e+07

In [36]:
# Filtering Groups: Use groupby and filter to find all rows belonging to genres that have fewer than 10 movies in the entire dataset.
df.groupby('genre').filter(lambda x: len(x) < 10)

,name,rating,genre,year,released,score,votes,director,writer,star,...,budget,gross,company,runtime,profit,release_country,release_date,score_category,duration_type,genre_avg_gross
40,The Watcher in the Woods,PG,Family,1980,"October 9, 1981 (United States)",6.3,5700.0,John Hough,Brian Clemens,Bette Davis,...,NaN,5000000.0,Walt Disney Productions,84.0,5000000.0,(United States),1981-10-09,Medium,Short,1.098218e+08
59,Hangar 18,PG,Sci-Fi,1980,"March 13, 1981 (Ireland)",5.3,2400.0,James L. Conway,Ken Pettus,Darren McGavin,...,11000000.0,NaN,Sunn Classic Pictures,97.0,NaN,(Ireland),1981-03-13,Medium,Standard,4.732608e+06
156,Eye of the Needle,R,Romance,1981,"July 24, 1981 (United States)",7.1,9900.0,Richard Marquand,Ken Follett,Donald Sutherland,...,NaN,17583634.0,Kings Road Entertainment,112.0,17583634.0,(United States),1981-07-24,Medium,Standard,9.121108e+06
162,Diva,R,Music,1981,"April 23, 1982 (United States)",7.2,12000.0,Jean-Jacques Beineix,Daniel Odier,Wilhelmenia Fernandez,...,NaN,110014.0,Les Films Galaxie,117.0,110014.0,(United States),1982-04-23,Medium,Standard,1.100140e+05
202,Comin' at Ya!,R,Western,1981,"July 24, 1981 (United States)",5.1,499.0,Ferdinando Baldi,Wolfe Lowenthal,Tony Anthony,...,NaN,12000000.0,Lupo-Anthony-Quintano Productions,91.0,12000000.0,(United States),1981-07-24,Medium,Standard,1.067530e+07
209,E.T. the Extra-Terrestrial,PG,Family,1982,"June 11, 1982 (United States)",7.8,381000.0,Steven Spielberg,Melissa Mathison,Henry Thomas,...,10500000.0,792910554.0,Universal Pictures,115.0,782410554.0,(United States),1982-06-11,High,Standard,1.098218e+08
287,Barbarosa,PG,Western,1982,"February 19, 1982 (United States)",6.4,1500.0,Fred Schepisi,William D. Wittliff,Willie Nelson,...,11000000.0,1736123.0,Incorporated Television Company (ITC),90.0,-9263877.0,(United States),1982-02-19,Medium,Standard,1.067530e+07
299,Jekyll and Hyde... Together Again,R,Sci-Fi,1982,"October 1, 1982 (United States)",6.2,1100.0,Jerry Belson,Monica Mcgowan Johnson,Mark Blankfield,...,5000000.0,3792188.0,Paramount Pictures,87.0,-1207812.0,(United States),1982-10-01,Medium,Short,4.732608e+06
323,Kamikaze 89,Not Rated,Sci-Fi,1982,"July 16, 1982 (West Germany)",5.8,665.0,Wolf Gremm,Robert Katz,Rainer Werner Fassbinder,...,NaN,22440.0,Regina Ziegler Filmproduktion,106.0,22440.0,(West Germany),1982-07-16,Medium,Standard,4.732608e+06
390,Brainstorm,PG,Sci-Fi,1983,"September 30, 1983 (United States)",6.4,11000.0,Douglas Trumbull,Bruce Joel Rubin,Christopher Walken,...,15000000.0,10219460.0,JF Productions,106.0,-4780540.0,(United States),1983-09-30,Medium,Standard,4.732608e+06
474,The Business of Show Business,NaN,History,1983,"February 15, 1983 (Canada)",8.3,79.0,Tom Logan,Tom Logan,NaN,...,323562.0,NaN,CTV,55.0,NaN,(Canada),1983-02-15,High,Short,NaN
521,Starman,PG,Romance,1984,"December 14, 1984 (United States)",7.0,44000.0,John Carpenter,Bruce A. Evans,Jeff Bridges,...,22000000.0,28744356.0,Columbia Pictures,115.0,6744356.0,(United States),1984-12-14,Medium,Standard,9.121108e+06
723,D.A.R.Y.L.,PG,Family,1985,"June 14, 1985 (United States)",6.3,12000.0,Simon Wincer,David Ambrose,Mary Beth Hurt,...,NaN,7840873.0,Paramount Pictures,99.0,7840873.0,(United States),1985-06-14,Medium,Standard,1.098218e+08
798,One Magic Christmas,G,Family,1985,"November 22, 1985 (United States)",6.5,3400.0,Phillip Borsos,Thomas Meehan,Mary Steenburgen,...,NaN,13677222.0,Walt Disney Pictures,89.0,13677222.0,(United States),1985-11-22,Medium,Short,1.098218e+08
942,The Manhattan Project,PG-13,Sci-Fi,1986,"June 13, 1986 (United States)",6.2,5600.0,Marshall Brickman,Marshall Brickman,John Lithgow,...,18000000.0,3900000.0,Gladden Entertainment,117.0,-14100000.0,(United States),1986-06-13,Medium,Standard,4.732608e+06
1029,Nutcracker,G,Family,1986,"November 26, 1986 (United States)",7.2,1000.0,Carroll Ballard,Kent Stowell,Hugh Duncan Bigney Mitchell,...,NaN,781727.0,Hyperion Pictures,89.0,781727.0,(United States),1986-11-26,Medium,Short,1.098218e+08
1381,36 fillette,NaN,Romance,1988,"January 6, 1989 (United States)",6.0,1200.0,Catherine Breillat,Catherine Breillat,Delphine Zentout,...,NaN,NaN,CB Films,88.0,NaN,(United States),1989-01-06,Medium,Short,9.121108e+06
1726,Hardware,R,Sci-Fi,1990,"September 14, 1990 (United States)",6.0,13000.0,Richard Stanley,Steve MacManus,Dylan McDermott,...,1500000.0,5728953.0,Palace Pictures,94.0,4228953.0,(United States),1990-09-14,Medium,Standard,4.732608e+06
2172,Love Crimes,R,Romance,1992,"January 24, 1992 (United States)",4.2,874.0,Lizzie Borden,Allan Moyle,Sean Young,...,NaN,2287928.0,Sovereign Pictures,90.0,2287928.0,(United States),1992-01-24,Low,Standard,9.121108e+06
2382,Posse,R,Western,1993,"May 14, 1993 (United States)",5.5,4200.0,Mario Van Peebles,Sy Richardson,Mario Van Peebles,...,10000000.0,18289763.0,PolyGram Filmed Entertainment,111.0,8289763.0,(United States),1993-05-14,Medium,Standard,1.067530e+07
2433,The Nutcracker,G,Family,1993,"November 24, 1993 (United States)",5.9,1900.0,Emile Ardolino,Susan Cooper,Darci Kistler,...,19000000.0,2119994.0,Krasnow Productions,92.0,-16880006.0,(United States),1993-11-24,Medium,Standard,1.098218e+08
2554,Miracle on 34th Street,PG,Family,1994,"November 18, 1994 (United States)",6.5,33000.0,Les Mayfield,Valentine Davies,Richard Attenborough,...,NaN,46264384.0,Twentieth Century Fox,114.0,46264384.0,(United States),1994-11-18,Medium,Standard,1.098218e+08
2597,Lassie,PG,Family,1994,"July 22, 1994 (United States)",5.9,5400.0,Daniel Petrie,Eric Knight,Helen Slater,...,NaN,9979683.0,Broadway Pictures,94.0,9979683.0,(United States),1994-07-22,Medium,Standard,1.098218e+08
3332,L'ennui,NaN,Romance,1998,"December 16, 1998 (France)",6.1,2000.0,Cédric Kahn,Cédric Kahn,Charles Berling,...,NaN,NaN,Gemini Films,122.0,NaN,(France),1998-12-16,Medium,Standard,9.121108e+06
3616,The Piano Player,Not Rated,Romance,1999,"October 21, 1999 (Germany)",7.8,7400.0,Rolf Schübel,Ruth Toma,Joachim Król,...,NaN,646532.0,Studio Hamburg Filmproduktion,112.0,646532.0,(Germany),1999-10-21,High,Standard,9.121108e+06
3820,The House of Mirth,PG,Romance,2000,"October 13, 2000 (United Kingdom)",7.0,7200.0,Terence Davies,Edith Wharton,Gillian Anderson,...,10000000.0,5164404.0,Three Rivers Production,135.0,-4835596.0,(United Kingdom),2000-10-13,Medium,Long,9.121108e+06
3831,Love's Labour's Lost,PG,Romance,2000,"March 31, 2000 (United Kingdom)",6.0,4400.0,Kenneth Branagh,William Shakespeare,Alessandro Nivola,...,13000000.0,299792.0,Pathé Pictures International,93.0,-12700208.0,(United Kingdom),2000-03-31,Medium,Standard,9.121108e+06

In [37]:
# Multi-Column Grouping: Calculate the total gross and total budget for every combination of year and genre.
df.groupby(['year','genre'])[['gross','budget']].sum().reset_index()

     year      genre         gross        budget
0    1980     Action  9.997018e+08  2.330000e+08
1    1980  Adventure  1.711924e+08  8.250000e+07
2    1980  Animation  2.180644e+06  0.000000e+00
3    1980  Biography  1.130398e+08  8.300000e+07
4    1980     Comedy  7.083826e+08  6.590000e+07
..    ...        ...           ...           ...
229  2001     Comedy  2.866142e+09  1.092800e+09
230  2001      Crime  1.125058e+09  4.057000e+08
231  2001      Drama  1.720300e+09  9.905000e+08
232  2001    Fantasy  2.718563e+08  1.100000e+08
233  2001     Horror  3.824913e+08  9.250000e+07

[234 rows x 4 columns]

In [38]:
# Sorting Aggregates: Find the top 10 directors based on the total sum of gross their movies have earned. Sort them from highest to lowest.
df.groupby('director')['gross'].sum().sort_values(ascending=False).head(10)

director
Steven Spielberg    5.223046e+09
James Cameron       3.400842e+09
Robert Zemeckis     3.095282e+09
Chris Columbus      2.734549e+09
Ron Howard          2.115348e+09
Roland Emmerich     1.644577e+09
Ivan Reitman        1.572119e+09
Tim Burton          1.555178e+09
Richard Donner      1.500066e+09
Michael Bay         1.479400e+09
Name: gross, dtype: float64

In [39]:
# Data Cleaning & Grouping: Some company names might have leading or trailing spaces. Strip the spaces from the company column first, then count how many movies each company has produced.
df['company'] = df['company'].str.strip()
df.groupby('company')['name'].count()

company
.406 Production                1
1+2 Seisaku Iinkai             1
13 Productions                 1
1492 Pictures                  2
1818 Productions               1
                              ..
Zeta Entertainment             1
Zoetrope Studios               7
Zucker Brothers Productions    1
Zupnik-Curtis Enterprises      1
double A Films                 1
Name: name, Length: 1305, dtype: int64

In [40]:
# Percentage Calculation: Group by genre and calculate the total votes for each. Then, calculate what percentage of the total votes (of all movies) each genre represents.
# 1. Total votes across the whole dataset
grand_total_votes = df['votes'].sum()

# 2. Total votes per genre divided by grand total
percentage_votes = (df.groupby('genre')['votes'].sum() / grand_total_votes) * 100

percentage_votes.sort_values(ascending=False)

genre
Action       27.660659
Comedy       21.426252
Drama        19.018308
Crime        10.098590
Adventure     6.211409
Animation     5.432561
Biography     4.980006
Horror        3.026483
Mystery       1.047131
Fantasy       0.811733
Family        0.203415
Romance       0.035313
Thriller      0.024264
Sci-Fi        0.015490
Music         0.005505
Western       0.002844
History       0.000036
Name: votes, dtype: float64

In [41]:
# Complex Aggregation: For each country, find the maximum runtime, the minimum score, and the sum of profit (assuming you have the profit column).
df.groupby('country')[['runtime','score','profit']].agg({'runtime':'max', 'score':'min', 'profit':'sum'})

                                runtime  score        profit
country
Argentina                         114.0    7.7  1.098372e+07
Aruba                              91.0    4.9 -1.968008e+07
Australia                         127.0    4.8  1.024349e+09
Austria                           105.0    6.4  2.389884e+07
Belgium                            95.0    7.5  2.055690e+05
Brazil                            120.0    7.4  2.008073e+07
Canada                            164.0    3.2  3.626304e+08
China                             171.0    7.7  9.044829e+06
Czech Republic                     96.0    5.2 -9.905470e+06
Denmark                           159.0    5.4  9.121902e+06
Federal Republic of Yugoslavia    167.0    8.1 -1.347747e+07
France                            238.0    4.5  8.080247e+08
Germany                           181.0    4.5  7.791233e+08
Greece                            176.0    7.6  0.000000e+00
Hong Kong                         109.0    3.7  3.958355e+08
Hungary                           145.0    5.7  2.546100e+04
India                             224.0    6.9  6.150249e+06
Iran                              118.0    7.5  4.576858e+06
Ireland                           134.0    5.4  9.749043e+07
Israel                            111.0    5.9  2.786230e+05
Italy                             229.0    3.9  2.390642e+08
Jamaica                            96.0    6.2  6.639390e+06
Japan                             202.0    4.0  1.143342e+09
Libya                             173.0    8.3  0.000000e+00
Mexico                            154.0    4.1  1.666536e+08
Netherlands                       144.0    6.7  1.864250e+07
New Zealand                       178.0    6.2  8.262781e+08
Norway                             96.0    7.3  2.275690e+05
Philippines                        86.0    4.3  1.723487e+06
Portugal                          140.0    5.8 -3.360791e+07
Republic of Macedonia             113.0    8.0 -1.136153e+06
Russia                            135.0    7.9 -4.865390e+05
South Africa                      117.0    4.3  4.041085e+07
South Korea                       140.0    2.7 -5.341325e+07
Soviet Union                      153.0    8.1  0.000000e+00
Spain                             128.0    6.1  2.974737e+08
Sweden                            188.0    5.9  2.652000e+07
Switzerland                       125.0    5.8  1.004104e+07
Taiwan                            173.0    7.6  2.110139e+08
United Kingdom                    357.0    3.2  4.406667e+09
United States                     271.0    2.2  8.751521e+10
Vietnam                           104.0    7.4  1.700992e+06
West Germany                      149.0    5.8  3.274692e+07
Yugoslavia                        144.0    5.0  4.233980e+06

In [42]:
########################################################################################################################################################

In [43]:
# 29. Named Aggregation (Report Generation): Group by genre. Create a summary table with three columns: movie_count, max_gross, and average_runtime. Use the named aggregation syntax: .agg(new_col=(col, func)).
summary = df.groupby('genre').agg(
    movie_count = ('name','count'),
    max_gross = ('gross','max'),
    average_runtime = ('runtime','mean')
)
summary

           movie_count     max_gross  average_runtime
genre
Action             775  1.033928e+09       105.936774
Adventure          231  1.006968e+09       106.181818
Animation          113  1.083721e+09        86.619469
Biography          175  3.221612e+08       122.428571
Comedy            1355  4.766847e+08       100.486347
Crime              302  4.507172e+08       111.480132
Drama              807  2.201647e+09       113.413879
Family               8  7.929106e+08        97.000000
Fantasy             33  2.060715e+08        99.090909
History              1           NaN        55.000000
Horror             158  2.486391e+08        95.449367
Music                1  1.100140e+05       117.000000
Mystery             13  2.213032e+08       113.615385
Romance              8  2.874436e+07       108.375000
Sci-Fi               6  1.021946e+07       101.166667
Thriller            11  4.492671e+07       101.090909
Western              3  1.828976e+07        97.333333

In [44]:
# 30. Broadcasting with Transform: Create a new column star_power. This column should contain the average score of all movies featuring that specific star. (Use .transform).
df['star_power'] = df.groupby('star')['score'].transform('mean')

In [45]:
# 31. Advanced Filtering: Use .filter() to return a DataFrame containing only the movies where the director has directed more than 15 movies in this dataset.
df.groupby('director').filter(lambda x: len(x) > 15)

,name,rating,genre,year,released,score,votes,director,writer,star,...,gross,company,runtime,profit,release_country,release_date,score_category,duration_type,genre_avg_gross,star_power
50,Stardust Memories,PG,Comedy,1980,"September 26, 1980 (United States)",7.3,22000.0,Woody Allen,Woody Allen,Woody Allen,...,10389003.0,Jack Rollins & Charles H. Joffe Productions,89.0,389003.0,(United States),1980-09-26,Medium,Short,3.108453e+07,7.015385
53,Bronco Billy,PG,Action,1980,"June 11, 1980 (United States)",6.1,11000.0,Clint Eastwood,Dennis Hackin,Clint Eastwood,...,24265659.0,Warner Bros.,116.0,17765659.0,(United States),1980-06-11,Medium,Standard,7.232715e+07,6.542105
117,The Fox and the Hound,G,Animation,1981,"July 10, 1981 (United States)",7.3,87000.0,Directors,Daniel P. Mannix,Mickey Rooney,...,63456988.0,Walt Disney Animation Studios,83.0,51456988.0,(United States),1981-07-10,Medium,Short,1.004415e+08,7.300000
233,Firefox,PG,Action,1982,"June 18, 1982 (United States)",6.0,26000.0,Clint Eastwood,Alex Lasker,Clint Eastwood,...,46708276.0,Major Studio Partners,136.0,28708276.0,(United States),1982-06-18,Medium,Long,7.232715e+07,6.542105
241,Diner,R,Comedy,1982,"May 21, 1982 (United States)",7.1,19000.0,Barry Levinson,Barry Levinson,Steve Guttenberg,...,14099953.0,Metro-Goldwyn-Mayer (MGM),110.0,9099953.0,(United States),1982-05-21,Medium,Standard,3.108453e+07,5.620000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3655,Space Cowboys,PG-13,Action,2000,"August 4, 2000 (United States)",6.4,75000.0,Clint Eastwood,Ken Kaufman,Clint Eastwood,...,128884132.0,Clipsal Films,130.0,63884132.0,(United States),2000-08-04,Medium,Standard,7.232715e+07,6.542105
3813,Small Time Crooks,PG,Comedy,2000,"May 19, 2000 (United States)",6.7,38000.0,Woody Allen,Woody Allen,Woody Allen,...,29934477.0,Dreamworks Pictures,94.0,4934477.0,(United States),2000-05-19,Medium,Standard,3.108453e+07,7.015385
3834,Digimon: The Movie,PG,Animation,2000,"October 6, 2000 (United States)",6.1,7000.0,Directors,Akiyoshi Hongo,Lara Jill Miller,...,16643191.0,Saban Entertainment,82.0,11643191.0,(United States),2000-10-06,Medium,Short,1.004415e+08,6.100000
3946,Bandits,PG-13,Comedy,2001,"October 12, 2001 (United States)",6.5,66000.0,Barry Levinson,Harley Peyton,Bruce Willis,...,67631903.0,Metro-Goldwyn-Mayer (MGM),123.0,-7368097.0,(United States),2001-10-12,Medium,Standard,3.108453e+07,6.623810
3958,Cowboy Bebop: The Movie,NaN,Animation,2001,"May 16, 2003 (United States)",7.9,44000.0,Directors,Keiko Nobumoto,Beau Billingslea,...,3007903.0,Bandai Visual Company,115.0,3007903.0,(United States),2003-05-16,High,Standard,1.004415e+08,7.900000

In [46]:
# 32. Mapping Values: Create a dictionary called genre_map that maps 'Action' to 'Exciting', 'Comedy' to 'Funny', and 'Horror' to 'Scary'. Create a new column genre_vibe using .map() with this dictionary. Challenge: Ensure other genres remain as they are and don't turn into NaN.
genre_map = {'Action':'Exciting','Comedy':'Funny','Horror':'Scary'}
df['genre_vibe'] = df['genre'].map(genre_map).fillna(df['genre'])
df['genre_vibe']

0           Drama
1       Adventure
2        Exciting
3           Funny
4           Funny
          ...
3995        Funny
3996        Funny
3997        Funny
3998        Funny
3999        Funny
Name: genre_vibe, Length: 4000, dtype: object

In [47]:
# 33. Handling Zeroes (The Proper Way): In the budget column, replace all 0 values with NaN and then fill those NaNs with the mean budget of the entire dataset. Ensure this change is saved to the main df.
df['budget'] = df['budget'].replace(0,np.nan)
df['budget'] = df['budget'].fillna(df['budget'].mean())
df['budget']

0       1.900000e+07
1       4.500000e+06
2       1.800000e+07
3       3.500000e+06
4       6.000000e+06
            ...
3995    1.300000e+07
3996    2.366166e+07
3997    5.000000e+06
3998    1.800000e+07
3999    7.000000e+07
Name: budget, Length: 4000, dtype: float64

In [48]:
# 34. Multi-Level Sorting: Sort the entire DataFrame first by year (Descending), and then within each year, sort by profit (Descending).
df = df.sort_values(by=['year','profit'], ascending=[False, False])

In [49]:
# 35. Cumulative Calculations: Create a new column cumulative_gross_by_director. This should show the running total (cumulative sum) of gross for each director, ordered by year.

# First sort by year so the 'running total' makes chronological sense
df = df.sort_values('year')
df['cumulative_gross_by_director'] = df.groupby('director')['gross'].cumsum()
df['cumulative_gross_by_director']

82        2806659.0
23       22762571.0
88        2261507.0
76        6321392.0
36       10000000.0
           ...
3900    648421426.0
3860    335373177.0
3844    596628021.0
3873    210325004.0
3852    461662924.0
Name: cumulative_gross_by_director, Length: 4000, dtype: float64

In [50]:
# 36. The apply logic (Multi-column): Create a new column is_blockbuster. A movie is a blockbuster (True/False) if its gross is more than 3 times its budget AND its score is higher than 7.0. Write a function and use .apply() with axis=1.

def check_blockbuster(row):
    if (row['gross'] > (3 * row['budget'])) and (row['score'] > 7.0):
        return True
    else:
        return False

# axis=1 tells pandas to feed the function one row at a time
df['is_blockbuster'] = df.apply(check_blockbuster, axis=1)

In [51]:
# 37. Date Extractions: From your release_date column (ensure it's datetime), create two new columns: release_year (as an integer) and is_weekend (a boolean True/False if the movie was released on a Saturday or Sunday).

# Ensure it is a datetime object first
df['release_date'] = pd.to_datetime(df['release_date'])

df['release_year'] = df['release_date'].dt.year
# .dt.dayofweek returns 5 for Saturday and 6 for Sunday
df['is_weekend'] = df['release_date'].dt.dayofweek.isin([5, 6])

In [52]:
# 38. Expert Pivot: Create a pivot table showing the sum of gross for each genre (as the index) across different years (as the columns). Fill any missing values in this pivot table with 0.
pivot_gross = df.pivot_table(index='genre', columns='year', values='gross', aggfunc='sum', fill_value=0)

In [53]:
#######################################################################################################################################################

In [59]:
# 39. Named Aggregation: Group by country. Create a summary table with two columns: total_gross_sum and max_score_achieved. Use the .agg(new_name=(col, func)) syntax.
df.groupby('country').agg(
   total_gross_sum = ('gross','sum'),
   max_score_achieved = ('score','max')
)

                                total_gross_sum  max_score_achieved
country
Argentina                          1.248372e+07                 7.9
Aruba                              1.031992e+07                 4.9
Australia                          1.502199e+09                 7.9
Austria                            5.389884e+07                 6.4
Belgium                            2.055690e+05                 7.5
Brazil                             2.298073e+07                 8.0
Canada                             9.690074e+08                 8.3
China                              1.304483e+07                 8.3
Czech Republic                     1.509453e+07                 5.2
Denmark                            5.822190e+07                 8.1
Federal Republic of Yugoslavia     5.225290e+05                 8.1
France                             2.085025e+09                 8.5
Germany                            1.929623e+09                 8.8
Greece                             0.000000e+00                 7.6
Hong Kong                          5.844355e+08                 8.1
Hungary                            2.546100e+04                 8.2
India                              1.365025e+07                 8.1
Iran                               4.906858e+06                 8.3
Ireland                            3.002904e+08                 8.1
Israel                             2.786230e+05                 6.3
Italy                              3.923642e+08                 8.6
Jamaica                            9.639390e+06                 6.2
Japan                              1.574642e+09                 8.6
Libya                              0.000000e+00                 8.3
Mexico                             2.002606e+08                 8.1
Netherlands                        1.864250e+07                 7.6
New Zealand                        9.772781e+08                 8.8
Norway                             2.275690e+05                 7.3
Philippines                        1.723487e+06                 4.3
Portugal                           6.392094e+06                 6.9
Republic of Macedonia              7.638470e+05                 8.0
Russia                             2.313461e+06                 7.9
South Africa                       4.541085e+07                 7.3
South Korea                        8.586749e+06                 7.0
Soviet Union                       0.000000e+00                 8.3
Spain                              3.199737e+08                 7.9
Sweden                             5.452000e+07                 8.1
Switzerland                        1.654104e+07                 8.1
Taiwan                             2.290139e+08                 8.2
United Kingdom                     8.462012e+09                 8.4
United States                      1.398489e+11                 9.3
Vietnam                            1.700992e+06                 7.4
West Germany                       8.274692e+07                 8.3
Yugoslavia                         7.233980e+06                 8.2

In [62]:
# 40. Broadcasting with Transform: Create a new column director_avg_runtime. This should show the average runtime of all movies made by that specific director.
df['director_avg_runtime'] = df.groupby('director')['runtime'].transform('mean')
df[['director','director_avg_runtime']]

                 director  director_avg_runtime
82            Jack Smight             97.000000
23       Robert Greenwald             96.000000
88           Mike Nichols            113.909091
76       Walter Bernstein            103.000000
36           Floyd Mutrux             95.000000
...                   ...                   ...
3900           Simon West            110.333333
3860   Jean-Pierre Jeunet            115.500000
3844            Rob Cohen            106.833333
3873   Alejandro Amenábar            111.500000
3852  Keenen Ivory Wayans             91.750000

[4000 rows x 2 columns]

In [81]:
# 41. Advanced Filtering: Use .filter() to return a DataFrame containing only the movies from companies that have produced more than 20 movies in this dataset.
df_large_companies = df.groupby('company').filter(lambda x: len(x) > 20)

In [69]:
# 42. Mapping Values: Create a dictionary that maps rating: 'R' $\rightarrow$ 'Adult', 'PG-13' $\rightarrow$ 'Teens', and 'PG' $\rightarrow$ 'Kids'. Create a new column rating_label and ensure other ratings (like 'G' or 'Not Rated') don't turn into NaN.
ratingdict = {'R':'Adult','PG-13':'Teens','PG':'Kids'}
df['rating_label'] = df['rating'].map(ratingdict).fillna(df['rating'])

In [83]:
# 43. Handling Zeroes: In the gross column, replace all 0 values with NaN and then fill those NaNs with the median gross of the entire dataset.
df['gross'] = df['gross'].replace(0, np.nan)
df['gross'] = df['gross'].fillna(df['gross'].median())

In [86]:
# 44. Multi-Level Sorting: Sort the entire DataFrame first by score (Descending: highest first), and then within each score, sort by budget (Ascending: cheapest first).
df.sort_values(by=['score','budget'],ascending=[False,True])

,name,rating,genre,year,released,score,votes,director,writer,star,...,star_power,genre_vibe,cumulative_gross_by_director,is_blockbuster,release_year,is_weekend,director_avg_runtime,rating_label,month_name,day_name
2443,The Shawshank Redemption,R,Drama,1994,"October 14, 1994 (United States)",9.3,2400000.0,Frank Darabont,Stephen King,Tim Robbins,...,7.000000,Drama,2.881729e+07,False,1994.0,False,161.000000,Adult,<bound method PandasDelegate._add_delegate_acc...,<bound method PandasDelegate._add_delegate_acc...
2444,Pulp Fiction,R,Crime,1994,"October 14, 1994 (United States)",8.9,1900000.0,Quentin Tarantino,Quentin Tarantino,John Travolta,...,5.721739,Crime,2.168424e+08,True,1994.0,False,135.666667,Adult,<bound method PandasDelegate._add_delegate_acc...,<bound method PandasDelegate._add_delegate_acc...
2247,Schindler's List,R,Biography,1993,"February 4, 1994 (United States)",8.9,1200000.0,Steven Spielberg,Thomas Keneally,Liam Neeson,...,6.688889,Biography,3.841901e+09,True,1994.0,False,140.500000,Adult,<bound method PandasDelegate._add_delegate_acc...,<bound method PandasDelegate._add_delegate_acc...
2445,Forrest Gump,PG-13,Drama,1994,"July 6, 1994 (United States)",8.8,1900000.0,Robert Zemeckis,Winston Groom,Tom Hanks,...,6.950000,Drama,2.203109e+09,True,1994.0,False,122.100000,Teens,<bound method PandasDelegate._add_delegate_acc...,<bound method PandasDelegate._add_delegate_acc...
3444,Fight Club,R,Drama,1999,"October 15, 1999 (United States)",8.8,1900000.0,David Fincher,Chuck Palahniuk,Brad Pitt,...,7.087500,Drama,6.977814e+08,False,1999.0,False,127.250000,Adult,<bound method PandasDelegate._add_delegate_acc...,<bound method PandasDelegate._add_delegate_acc...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Inchon,PG,Drama,1981,"September 17, 1982 (United States)",2.7,659.0,Terence Young,Robin Moore,Laurence Olivier,...,5.166667,Drama,5.200986e+06,False,1982.0,False,140.000000,Kids,<bound method PandasDelegate._add_delegate_acc...,<bound method PandasDelegate._add_delegate_acc...
1125,The Garbage Pail Kids Movie,PG,Adventure,1987,"August 22, 1987 (United States)",2.6,7600.0,Rod Amateau,Linda Palmer,Anthony Newley,...,2.600000,Adventure,1.576615e+06,False,1987.0,True,96.500000,Kids,<bound method PandasDelegate._add_delegate_acc...,<bound method PandasDelegate._add_delegate_acc...
2995,Lawnmower Man 2: Beyond Cyberspace,PG-13,Action,1996,"January 12, 1996 (United States)",2.5,9000.0,Farhad Mann,Farhad Mann,Patrick Bergin,...,4.850000,Exciting,2.409225e+06,False,1996.0,False,93.000000,Teens,<bound method PandasDelegate._add_delegate_acc...,<bound method PandasDelegate._add_delegate_acc...
3684,Battlefield Earth,PG-13,Action,2000,"May 12, 2000 (United States)",2.5,77000.0,Roger Christian,Corey Mandell,John Travolta,...,5.721739,Exciting,3.271553e+07,False,2000.0,False,105.000000,Teens,<bound method PandasDelegate._add_delegate_acc...,<bound method PandasDelegate._add_delegate_acc...
1189,Leonard Part 6,PG,Action,1987,"December 18, 1987 (United States)",2.2,7900.0,Paul Weiland,Jonathan Reynolds,Bill Cosby,...,3.300000,Exciting,4.615255e+06,False,1987.0,False,100.500000,Kids,<bound method PandasDelegate._add_delegate_acc...,<bound method PandasDelegate._add_delegate_acc...

In [87]:
# 45. Cumulative Calculations: Create a new column cumulative_votes_by_genre. This should show the running total of votes for each genre, ordered by year.
df = df.sort_values('year')
df['cumulative_votes_by_genre'] = df.groupby('genre')['votes'].cumsum()

In [88]:
# 46. The apply logic (Multi-column): Create a new column is_legendary. A movie is legendary (True/False) if its score is higher than 8.5 AND it has more than 500,000 votes.
def legend(row):
  if(row['score']>8.5) and (row['votes']>50000):
    return True
  else:
    return False

df['is_legendary'] = df.apply(legend, axis=1)
df['is_legendary']

6       False
17      False
19      False
41      False
47      False
        ...
3844    False
3873    False
3852    False
3903    False
3920    False
Name: is_legendary, Length: 4000, dtype: bool

In [89]:
# 47. Date Extractions: From your release_date column, create two new columns: month_name (e.g., January, February) and day_name (e.g., Monday, Tuesday).
df['month_name'] = df['release_date'].dt.month_name()
df['day_name'] = df['release_date'].dt.day_name()
df[['release_date','month_name','day_name']]

     release_date month_name   day_name
6      1980-06-20       June     Friday
17     1980-12-19   December     Friday
19     1980-12-12   December     Friday
41     1980-07-03       July   Thursday
47     1980-11-07   November     Friday
...           ...        ...        ...
3844   2001-06-22       June     Friday
3873   2001-08-10     August     Friday
3852   2001-07-04       July  Wednesday
3903   2001-04-06      April     Friday
3920   2002-01-25    January     Friday

[4000 rows x 3 columns]

In [90]:
# 48. Expert Pivot: Create a pivot table showing the average score for each director (index) across different ratings (columns). Fill missing values with 0.
df.pivot_table(index='director', columns='rating', values='score', aggfunc='mean', fill_value=0)

rating,Approved,G,NC-17,Not Rated,PG,PG-13,R,TV-MA,TV-PG,Unrated,X
director,,,,,,,,,,,
Aaron Norris,0.0,0.0,0.0,0.000000,5.1,4.2,5.150000,0.0,0.0,0.0,0.0
Abbas Kiarostami,0.0,7.8,0.0,7.866667,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
Abel Ferrara,0.0,0.0,7.1,6.500000,0.0,0.0,6.083333,0.0,0.0,0.0,0.0
Adam Bernstein,0.0,0.0,0.0,0.000000,0.0,2.7,0.000000,0.0,0.0,0.0,0.0
Adam Brooks,0.0,0.0,0.0,0.000000,0.0,0.0,5.100000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
Álex de la Iglesia,0.0,0.0,0.0,0.000000,0.0,0.0,7.400000,0.0,0.0,0.0,0.0
Édouard Molinaro,0.0,0.0,0.0,0.000000,5.9,0.0,5.800000,0.0,0.0,0.0,0.0
Élie Chouraqui,0.0,0.0,0.0,0.000000,0.0,0.0,6.500000,0.0,0.0,0.0,0.0
Éric Rohmer,0.0,7.6,0.0,7.450000,7.4,0.0,7.550000,0.0,0.0,0.0,0.0
Éva Gárdos,0.0,0.0,0.0,0.000000,0.0,6.7,0.000000,0.0,0.0,0.0,0.0